export class PAGE_PATH {
  static readonly SEARCH_PAGE: string = "SearchView" // 搜索页
  static readonly SEARCH_RESULT_PAGE: string = "SearchResultView"
  static readonly LOGIN_PAGE: string = "LoginView" // 登录页
  static readonly SETTINGS_PAGE: string = "SettingsView" // 登录页
  static readonly GOODS_PAGE: string = "GoodsView" // 商品详情页
  static readonly CART_PAGE: string = "CartView" // 购物车页面
  static readonly CHECK_ORDER_PAGE: string = "CheckView" // 核对订单页面
  static readonly PAY_PAGE: string = "PayView" // 支付宝沙箱支付页面
  static readonly PAY_RESULT_PAGE: string = "PayResultView" // 支付结果页
}